# kustomize-sample/overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namePrefix: staging-

patches:
- path: replicas.yaml
  target:
    kind: Deployment
    name: my-app
